### ISSUE TITLE
Create a can_see_mediafile query

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-permission-service#125]
An allowed check for retriving mediafiles is needed for checking, if the media service is allowed to deliver a file to a user. So the input is a user id and a mediafile id (Note: the request is only done for actual files, but the logic is independend if a mediafile is a file or a directory I think).

let **the meeting** be the meeting of the mediafile.

The user can see the mediafile, if
- He is superadmin
- He is admin in the meeting
- Cannot see, if not in meeting
- He has mediafile.can_see and (is in a group of `inherited_access_group_ids` (Note: default groups do count!) or `is_public` is true).
- The mediafile is a special file (used as at least one logo or font)
- The mediafile is currently projected (at least one entry in `mediafile/current_projector_ids`) and the user has projector.can_see

**Comment by ostcar** [comment]
@FinnStutzenstein Is a db like this valid?
```
mediafile/1/meeting_id  = 1
mediafile/1/used_as_logo_$frontpage_in_meeting_id = 2
```
So a mediafile from meeting 1 can be a logo in meeting 2?

**Comment by ostcar** [comment]
@FinnStutzenstein please have a look at the test-file in https://github.com/OpenSlides/openslides-permission-service/pull/128

I this correct?

The mediafile collection has the filed `is_public` is this also relevant?

**Comment by FinnStutzenstein** [comment]
> So a mediafile from meeting 1 can be a logo in meeting 2?

No

> The mediafile collection has the filed `is_public` is this also relevant?

Yes, I overlooked the access part with the dedicated access groups. I updated the description above.

**Comment by ostcar** [comment]
@FinnStutzenstein could you have another look over the test?

https://github.com/OpenSlides/openslides-permission-service/blob/b295f1976ea5676251c3338af2ebaea887437b6c/tests/mediafile/can_see_mediafile.yml

**Comment by FinnStutzenstein** [comment]
Please duplicate the `on projector` three times:
- without the `projector.can_see`
- without the `current_projector_id`
- with the user being in a different meeting.

It looks good so far

**Comment by ostcar** [comment]
I added the tree new test cases. I am not sure in I understand you correctly. Please have a look at the new commit:

https://github.com/OpenSlides/openslides-permission-service/pull/128/commits/cc8be85ec05c1d3da668ea0a19e13c53aca43541

**Comment by ostcar** [comment]
@FinnStutzenstein: What do you mean with "He is admin in the meeting". Do you mean the request user is in the field `meeting/X/admin_group_id` or you you mean the request user has the permission `mediafile.can_manage`?

Currently, a user with `mediafile.can_manage` can not see mediafiles where `is_public=false` or is not in `inherited_access_group_ids`.

**Comment by FinnStutzenstein** [comment]
I think the mediafile manager should always see every file. so if the user is an admin or has `mediafile.can_manage`, he can see the mediafile.
