### ISSUE TITLE
Allow development of other components by enabling is_allowed on errors

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-permission-service#148]
On 5xx errors (so non-valid is_allowed responses), log it and send a 200 with `true`. This blocks the development of other parts of OpenSlides (3 devs reported this issue to me this morning blocking their work.)

@GabrielInTheWorld @r-peschke @reiterl

**Comment by ostcar** [comment]
I can do this tomorrow. If you need the fix today, maybe the backend can do it? (when 500 is received, log the message and handel it as success.)
