### ISSUE TITLE
Proposal: Add new GitHub action to validate permissions.yml

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#158]
After https://github.com/OpenSlides/OpenSlides/pull/5836 is merged you may add a new GitHub action to check that permissions.yml does contain all perms that are in the models.yml list (and not more or other). This is to get a hint on further changes.

**Comment by ostcar** [comment]
As we talked about it, there will not be an action in this repo to validate the permission.yml
