### ISSUE TITLE
Create config map for permissions

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#160]
See https://github.com/OpenSlides/openslides-permission-service/issues/28.

**Comment by ostcar** [comment]
I don't want to go to all the issues from the coordination issue. I wont fix this.

@emanuelschuetze this is important

**Comment by normanjaeckel** [comment]
What is the status of this issue now?

**Comment by jsangmeister** [comment]
Well, it seems like someone has to create this config map for @ostcar. Feel free to do it ;)

**Comment by ostcar** [comment]
Since I was the only one requesting this and I am not responsible anymore for action permissions, I close this issue.
