### ISSUE TITLE
Remove permission.yml

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#163]
Remove the file here after https://github.com/OpenSlides/OpenSlides/pull/5855 is merged.

**Comment by normanjaeckel** [comment]
PR in main repo is merged.

**Comment by ostcar** [comment]
I have to fix the go generate-skript in this repo. Please tell me when you moved the permission-file to the main repo. Afterwards, I will make the changes here.

**Comment by normanjaeckel** [comment]
The main repo now contains the permission.yml so you can delete it here and fix your scripts.

**Comment by normanjaeckel** [comment]
@ostcar May have a look at this.

**Comment by ostcar** [comment]
See #164
