### ISSUE TITLE
Do not check for settings

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-permission-service#167]
E.g. user.set_present: It should be allowed if the request user == user in payload else the request user has user.can_manage (or anything higher)

Edit: I changed the check above

Please make sure, that no settings are used in the permission service (Except permission/auth-relevant ones like `enable_anonymous`). The reason is that we need a clear line, what is checked here and in the backend to avoid both scenarios: Duplicated checks (like user.set_present) or missed checks since everyone thinks the other service has done it. I would like to see *only* these checks in the permission service:
- is the user id right (e.g. no anonymous)
- role
- permissions inside a meeting
- access checks for models through groups (like motion_comment_sections)

Additionally, these rules should be clear to the backend. @jsangmeister @normanjaeckel 

Whats your opinion on this?

**Comment by jsangmeister** [comment]
Yes, this is the line we currently follow in the backend. We assume the permissions are correct and check additional things like settings etc.

One exception: For some actions, we check if the user is anonymous (e.g. `set_password_self` or `personal_note.create`, which are not permitted fr anonymous). Should this checks be removed and the permission service does that instead?
