### ISSUE TITLE
More information in case of server error 500

### ISSUE THREAD

**Issue by r-peschke** [OpenSlides/openslides-permission-service#168]
Please give more information about Action.name and payload. This could be in logging.debug, preferred, or in Exception.message.

For instance these are the logs I got this morning from an action with nested actions:
backend_1           | DEBUG:urllib3.connectionpool:http://permission:9005 "POST /internal/permission/is_allowed HTTP/1.1" 500 99
backend_1           | DEBUG:openslides_backend.services.permission.adapter:Permission service response with status code 500: Internal Error. Norman, Do not sent it to client: payload 0: no valid meeting_id or id in payload
backend_1           | ERROR:openslides_backend.services.permission.adapter:Permission service sends HTTP 500 with the following content: Internal Error. Norman, Do not sent it to client: payload 0: no valid meeting_id or id in payload.

**Comment by ostcar** [comment]
What error message would you like instead?

**Comment by r-peschke** [comment]
> What error message would you like instead?

Minimum should be the Action.name and the payload.  Now you only give some missing payload fields, without referring to action.name and given payload. 
In the concret case I identified the action as speaker.sort. This has only 2 required fields, list_of_speakers_id and speaker_ids. What payload/schema do you refer to?
Yesterday we changed the sequence in backend. Now we first check the action-payload against the schema for this action, before asking for permissions.
We also changed the condition, when the permission service gets called. On internally actions, initiated by the logic ofthe backend-server, we don't ask the permission service anymore (Current case: speaker.create with internally action speaker.sort, in some cases of Point-of-order-speaker necessary). 
Now I get the same error in client call to speaker.sort (initiated by changing the order of speaker items manually in the GUI). The following are the results, enriched by some logger.debug-informations ffrom backend:

```
backend_1           | DEBUG:openslides_backend.shared.handlers.base_handler:Perform action speaker.sort.
backend_1           | DEBUG:openslides_backend.action.action:Action name: speaker.sort
backend_1           |  Schema: {'$schema': 'http://json-schema.org/draft-07/schema#', 'title': 'Sort speaker schema', 'description': None, 'type': 'object', 'properties': {'list_of_speakers_id': {'type': 'integer', 'minimum': 1}, 'speaker_ids': {'type': 'array', 'items': {'type': 'integer', 'min': 1}, 'minItems': 1, 'uniqueItems': True}}, 'required': ['list_of_speakers_id', 'speaker_ids'], 'additionalProperties': False}
backend_1           |  Payload: [{'list_of_speakers_id': 3, 'speaker_ids': [37, 36, 48, 44]}]
backend_1           | DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): permission:9005
datastore-reader_1  | 2021-02-12T09:52:32.932: [/app/reader/flask_frontend/json_handler.py] [INFO] GET_MANY-request: {'requests': ['user/2/organisation_management_level']}
datastore-reader_1  | 172.24.0.9 - - [12/Feb/2021 09:52:32] "POST /internal/datastore/reader/get_many HTTP/1.1" 200 -
backend_1           | DEBUG:urllib3.connectionpool:http://permission:9005 "POST /internal/permission/is_allowed HTTP/1.1" 500 99
backend_1           | DEBUG:openslides_backend.services.permission.adapter:Permission service response with status code 500: Internal Error. Norman, Do not sent it to client: payload 0: no valid meeting_id or id in payload
backend_1           | ERROR:openslides_backend.services.permission.adapter:Permission service sends HTTP 500 with the following content: Internal Error. Norman, Do not sent it to client: payload 0: no valid meeting_id or id in payload.
```

**Comment by ostcar** [comment]
@r-peschke I added the action name and the payload. Please test #169 and tell me, if this is ok for you. If you need more infos (and if so, which infos)
