### ISSUE TITLE
Missing $

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#17]
In https://github.com/OpenSlides/openslides-permission-service/blob/573a84541d545a7873061969341ab53030ec6b2f/internal/allowed/helpers.go#L148 there is a `$` missing.

**Comment by normanjaeckel** [comment]
Also in https://github.com/OpenSlides/openslides-permission-service/blob/master/internal/tests/shared.go#L176

**Comment by ostcar** [comment]
Both is solved
