### ISSUE TITLE
Remove old permission

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-permission-service#185]
`user.can_change_own_password` was removed and replaced with the collection field `user/can_change_own_password`

**Comment by ostcar** [comment]
Is this relevant? The permission is only used in the action "user.set_password_self". All actions should be implemented by the backend service. Was this action already be implemented in python? If so, we can close this here.

**Comment by FinnStutzenstein** [comment]
Ok,
I just wanted to check, that it is not used somewhere else.
