### ISSUE TITLE
Implement speaker.create

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#24]

**Comment by normanjaeckel** [comment]
If users wants to add himself to list of speakers (via speaker creation) he has to have `agenda.can_be_speaker`. To add someone else he must have `agenda.can_manage_list_of_speakers`.

**Comment by normanjaeckel** [comment]
Permission change to something with `list_of_speakers`

**Comment by ostcar** [comment]
With the perm `list_of_speakers.can_manage`: is it possible to add someone who does not have the perm `list_of_speakers.can_be_speaker`?

If yes: It seams wrong that the permission `list_of_speakers.can_be_speaker` has to meanings. It means, that someone can put himself on the list of speaker AND is a requirement  to be put on the list by a manager.

**Comment by ostcar** [comment]
The current implementation is funny. The permission `list_of_speakers.can_manage` does not automatically give the permission `list_of_speakers.can_be_speaker`. So a manager can add any other user but not himself (because in this case he would need the perm `list_of_speakers.can_be_speaker`). :)

**Comment by normanjaeckel** [comment]
It is possible to add someone who does not have can_be_speaker to the list. But not himself of course. So can_be_speaker is not a requirement to be put on the list by a manager.

**Comment by ostcar** [comment]
@FinnStutzenstein why did you unassign emanuel?

**Comment by ostcar** [comment]
I talked with emanuel. It is correct, that the manager can assign himself. This is the current implementation. I will add some tests to prove it.
