### ISSUE TITLE
Implement assignment_candidate.create

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#26]

**Comment by normanjaeckel** [comment]
`assignments.can_nominate_self` if the user wants to create "himself", for all others: `assignments.can_nominate_other`.

During voting (assignment phase) you have to have `assignment.can_manage`

**Comment by ostcar** [comment]
There are three phases: https://github.com/OpenSlides/OpenSlides/blob/ea277adf9ead6fabc0959524db377d996c4a6ea1/server/openslides/assignments/models.py#L100-L102

I think, only the manager can create candidates in phase 1 and 2. So only in the phase 0 the permissions "can_nomiate_self" and "can_nomiate_other" are relevant.

I implement it this way. If I am wrong, then please reopen

**Comment by normanjaeckel** [comment]
Keep in mind that during voting, assignment.can_manage is not sufficient if the user wants to nominate himself.

**Comment by ostcar** [comment]
The permission `assignment.can_nominate_other` does not give the permission `assignment.can_nominate_self`. Can someone with `can_nomidate_other` nominate himself?

**Comment by ostcar** [comment]
> Keep in mind that during voting, assignment.can_manage is not sufficient if the user wants to nominate himself.

I don't understand what you mean. It is not possible to add the request-user in the voting phase but it is possible to add other users in the voting phase?

**Comment by ostcar** [comment]
> > Keep in mind that during voting, assignment.can_manage is not sufficient if the user wants to nominate himself.
> 
> I don't understand what you mean. It is not possible to add the request-user in the voting phase but it is possible to add other users in the voting phase?

Is this true only for the phase `voting` or also for the phase `finished`? So has a manager  the permission to add himself to a finished assignment? Can he add others?

**Comment by normanjaeckel** [comment]
Please talk to @emanuelschuetze

**Comment by ostcar** [comment]
Talked to emanuel. The current implementation is correct: The manager can assign himself
