### ISSUE TITLE
Implement assignment_candidate.delete

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#27]

**Comment by normanjaeckel** [comment]
The same as for assignment_candidate.create.

But for deleting others you need `assignment.can_manage`. `assignment.can_nominate_other` is not sufficient.

**Comment by normanjaeckel** [comment]
Deleting yourself is possible in every state with assignment.can_manage.

**Comment by ostcar** [comment]
> Deleting yourself is possible in every state with assignment.can_manage.

Is it also possible to delete others with that perm?

**Comment by normanjaeckel** [comment]
Conclusion:

Delete yourself:
- Either assignment.can_manage or assignment.can_nominate_self (but only in first state).

Delete other:
- assignment.can_manage

**Comment by ostcar** [comment]
Already done
