### ISSUE TITLE
Implement motion_submitter.create

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#35]

**Comment by normanjaeckel** [comment]
Only managers with motion.can_manage can add new submitters to any motion. @FinnStutzenstein Correct?

**Comment by FinnStutzenstein** [comment]
No, you just need `motion.can_manage_metadata`.

**Comment by ostcar** [comment]
@normanjaeckel In this case, please fix this in the backend

**Comment by normanjaeckel** [comment]
Will be done with https://github.com/OpenSlides/openslides-backend/pull/380

**Comment by ostcar** [comment]
I have to regenerate this in the permission service

**Comment by normanjaeckel** [comment]
You can do it now (or later of course).

**Comment by normanjaeckel** [comment]
Please check if this is correctly implemented because we have no permission strings in the backend anymore.
