### ISSUE TITLE
Implement motion.create

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#36]

**Comment by normanjaeckel** [comment]
If it is an amendment creation then motion.can_create_amendment is required, else motion.can_create is required.

If motion.can_manage is not present, only a whitelist of fields can be used: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/views.py#L168 (also parent_id and amendment_paragraphs if it is an amendment).

**Comment by ostcar** [comment]
@normanjaeckel In the current [permissions.yml](https://github.com/OpenSlides/openslides-permission-service/blob/21103de88778e7bc70be6f298980956d1567e340/permissions.yml), motion.can_create_amendment and motion.can_create are two separate permissions. Is this by purpose?

**Comment by ostcar** [comment]
@normanjaeckel how can I find out if it is an amendment? With the key "origin_id"?

**Comment by normanjaeckel** [comment]
`parent_id` should be None if it is not an amendment and should be set if it is. `origin` is something else and has nothing to do with amendments.

**Comment by ostcar** [comment]
I already did this
