### ISSUE TITLE
Implement personal_note.create

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#43]

**Comment by normanjaeckel** [comment]
Only for request user himself (user_id == request user).

**Comment by ostcar** [comment]
I don't think there is a user_id in the payload. Only a content_object_id.

Can everyone != anonymous create personal_notes? Does the user need read permissions for this object? What if the read-permission changes? Is the user still allowed to update the note?

**Comment by normanjaeckel** [comment]
I think every user != anonymous can create his own personal notes regardless of a can see permission.

**Comment by ostcar** [comment]
see update

**Comment by normanjaeckel** [comment]
Here the permission service does not have to check anything.

**Comment by normanjaeckel** [comment]
EDIT: The permission service must ensure that the request user can see the content object. It should not be possible to create personal notes to arbitrary objects of all meetings ever (e. g. a client sends random content_object_ids to spam the DB).

**Comment by ostcar** [comment]
This is not as easy as it sounds. I currently don't have a function to check "can_see_fqid" and it would be hard to implement it. (How would you check it, with fqid+ "/id"? :) )

So this is a wont fix.
