### ISSUE TITLE
Implement user.set_password_self

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#55]

**Comment by normanjaeckel** [comment]
Everybody can change its own password. @FinnStutzenstein Right? The meeting perm user.can_change_own_password is only relevant for temporary users.

**Comment by FinnStutzenstein** [comment]
currentl yes, right.

**Comment by ostcar** [comment]
I thought temporary users are also user objects. So I have to check if the request user is a temporary user?

**Comment by normanjaeckel** [comment]
Yes.

**Comment by ostcar** [comment]
Already done
