### ISSUE TITLE
Implement user.update_self

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#57]

**Comment by normanjaeckel** [comment]
You need `organisation_management_level` `is_superuser`, `can_manage` or `can_manage_users`

If not, you can update yourself only for the field `about_me_$` and its populated fields.

**Comment by ostcar** [comment]
@normanjaeckel as discussed: Please change the backend. Do not send the user-id in the payload, just use the request-user-id. Also, do not accept other fields then "about_me_$" in the payload.

**Comment by normanjaeckel** [comment]
Please check again: `user_id` is not part of the payload.

**Comment by normanjaeckel** [comment]
I think the others want that email and username can also be changed: https://github.com/OpenSlides/openslides-backend-coordination/issues/141

**Comment by ostcar** [comment]
The backend is parsing the payload. The action returns true, if the user_id is not 0. Then all fields can be updated, that are allowed in the payload.
