### ISSUE TITLE
Implement read permission: poll, option. vote

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#64]
Reading a poll and its related options and votes depends on the content object:

For assignment you need assignment.can_see, for motion motion.can_see.

If the poll is not in published state (poll.state != 4) some fields have to be restricted: See https://github.com/OpenSlides/OpenSlides/blob/ea277adf9ead6fabc0959524db377d996c4a6ea1/server/openslides/poll/access_permissions.py#L112

This might be also relevant for option and vote.

**EDIT: Unlimited access is given with the respective manage permission.**

**Comment by ostcar** [comment]
What is the required permission, when there is a stand alone poll? https://github.com/OpenSlides/OpenSlides/blob/a3dce30e1df12f72316eafa2d42461a5c07487d8/docs/models.yml#L1501

**Comment by normanjaeckel** [comment]
I dont know. Lets assume agenda.can_manage for unlimited access and limited read access for all meeting participants (with anonymous if enabled).

**Comment by ostcar** [comment]
@FinnStutzenstein can you give me a positive list of fields that can be seen by non-managers when the poll is not published?

**Comment by normanjaeckel** [comment]
Votes: Own vote and delegated vote are visible with *.can_see. Else you need *.can_manage or poll must be published and you have *.can_see

**Comment by normanjaeckel** [comment]
Option: Visible with *.can_see and poll is published. If poll is not published you need *.can_manage. If not (but you have at least *.can_see), the follwing fields a restricted: yes, no, abstain.

**Comment by normanjaeckel** [comment]
Poll: The same as for option: The following fields are restricted: votesvalid, votesinvalid, votescast, voted_ids, global_yes, global_no, global_abstain

**Comment by normanjaeckel** [comment]
Attention: For motions it is motion.can_manage_polls and for assignment it is only assignment.can_manage.

**Comment by normanjaeckel** [comment]
Keep in mind that in simple case polls and options and votes of internal motions can not be seen only `motion.can_see `but `motion.can_see_internal`

**Comment by ostcar** [comment]
This was already done

**Comment by ostcar** [comment]
Tested for motion-polls.

TODO: Assignment-polls and other-polls

**Comment by FinnStutzenstein** [comment]
> Option:If poll is not published you need *.can_manage.

This sounds wrong since users must see what to vote about.

**Comment by FinnStutzenstein** [comment]
For polls:

> Poll: The same as for option: The following fields are restricted: votesvalid, votesinvalid, votescast, voted_ids, global_yes, global_no, global_abstain

global_yes global_no and global_abstain can be seen since they are flags, if these features are enabled. They do not contain actual vote values.

**Comment by ostcar** [comment]
> > Option:If poll is not published you need *.can_manage.
> 
> This sounds wrong since users must see what to vote about.

So I change it to *.can_see?

**Comment by ostcar** [comment]
@FinnStutzenstein Please explain me again how the option works.

The current implementation is the following.

If the user has `can_manage` he can see every field.

If the user does not have `can_see` he can see nothing.

If the relevant poll is published, a user with `can_see` sees every field.

If the relevant poll is not published, the user sees every field, expect `yes`, `no` and `abstain`.

Is this correct?

**Comment by FinnStutzenstein** [comment]
This sounds good. We can think about restricting `vote_ids`, too, so a user cant see if there are votes, but this is a minor one I think.

**Comment by ostcar** [comment]
I made all changes in PR #124

Here are the tests for unpublished polls. Is this correct? https://github.com/OpenSlides/openslides-permission-service/pull/124/files#diff-e2ca492755319ed08bb8a0bd637e817779e72fc935b031e6e4bc8e008e6ff289

**Comment by FinnStutzenstein** [comment]
I've added a small comment. looks good so far
