### ISSUE TITLE
Implement read permission: agenda_item and topic

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#65]
agenda_item and topic can be seen with agenda.can_see.

For agenda_items with is_hidden == True you need agenda.can_manage. For agenda_items with is_internal == True you need agenda.can_see_internal_items

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/OpenSlides/blob/ea277adf9ead6fabc0959524db377d996c4a6ea1/server/openslides/agenda/access_permissions.py#L46

**Comment by normanjaeckel** [comment]
But even if you can see agenda_items, some keys are restricted: `duration` can only be read with `agenda.can_see_internal_items`. `comment` can only be read with `agenda.can_manage`.

**Comment by ostcar** [comment]
In the models.yml, `agenda_item.is_internal` and `agenda_item.is_hidden` are two distinct fields. What if a agenda_item is hidden and internal? Is `agenda.can_see_internal_items` enough to see it?

https://github.com/OpenSlides/OpenSlides/blob/a3dce30e1df12f72316eafa2d42461a5c07487d8/docs/models.yml#L832

**Comment by ostcar** [comment]
@normanjaeckel in pr #72 I implmented, that a hidden and internal-item can only be seen with the can_manage perm

If this was not ok, please reopen.

**Comment by normanjaeckel** [comment]
The permissions changed: They are now called `agenda_item.can_see`, `agenda_item.can_see_internal` and `agenda_item.can_manage`

**Comment by ostcar** [comment]
already done
