### ISSUE TITLE
Set all organisation level actions to superuser

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#76]
Please set all orga level actions to be used by superuser only. For the first draft ...

**Comment by normanjaeckel** [comment]
Orga level read permissions? I am not sure. Maybe set them for free for everybody for the moment.

**Comment by ostcar** [comment]
The current implementation has a "development-mode" enabled. Every action or collection that is not implemented can be seen by everyone.

When every action is implemented, i will remove this "development-mode".

Until we have decided how to handle organisations, there is nothing to do.

The superuser is currently not checked. First, I want to discuss the "additional-data" return value.
