### ISSUE TITLE
Implement read permission: meeting

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#79]

**Comment by normanjaeckel** [comment]
Every member of the meeting (including anonymous, if enabled) can see the meeting and all its properties.

@FinnStutzenstein Are there some secret settings like passwords for jitsi room etc.?

**Comment by ostcar** [comment]
I added a implementation, where a member can see every field.

@FinnStutzenstein If this is correct, then please close this issue

**Comment by normanjaeckel** [comment]
Please restrict some keys:
`meeting.can_see_frontpage` is required for welcome_title and welcome_text of the frontpage.
`meeting.can_see_livestream` is required for conference_stream_url, conference_stream_poster_url.

**Comment by normanjaeckel** [comment]
Also: `enable_anonymous` should be always present, even for anonymous if anonymous is not enabled.

**Comment by ostcar** [comment]
> Also: `enable_anonymous` should be always present, even for anonymous if anonymous is not enabled.

This means, that `meeting/X/id` is also present for everyone.

**Comment by ostcar** [comment]
@normanjaeckel  Is it correct, that someone with the permission "meeting.can_manage_settings" has not automatically the permission to see the frontpage? What permission does a user need to change the text of the frontpage? both?

**Comment by normanjaeckel** [comment]
Is this an open question? Please ask @emanuelschuetze about the relation of "meeting.can_see_frontpage" and "meeting.can_manage_settings".

**Comment by ostcar** [comment]
@emanuelschuetze ping
