### ISSUE TITLE
Implement read permission: motion

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#80]

**Comment by normanjaeckel** [comment]
User with `motions.can_manage` can see all motions. All others must at least have `motions.can_see` and they must pass some extra checks, see https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/access_permissions.py#L13: Check the field restrictions of the state of the motions. If this field is an empty list, the motion is free. If not, it is available only if the user fullfills one of the restrictions (only one is required not all).

**Comment by ostcar** [comment]
The values in the restrictions fields are `motions.*` But the permissions are called `motion.*` Could you change this in the models.yml and the backend? I will implement it with motion as singular.

**Comment by normanjaeckel** [comment]
Also `motion.can_see_internal` is required for internal motions.

**Comment by ostcar** [comment]
already done

**Comment by ostcar** [comment]
@normanjaeckel In the current implementation: If a submitter does not have the perm "can_see" he can not see his own motions. Is this correct?

Also, a supporter has no special permissions for "his" motions.

**Comment by normanjaeckel** [comment]
Yes I think
