### ISSUE TITLE
Implement read permission: motion_comment

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#84]

**Comment by normanjaeckel** [comment]
The user must be able to see at least one field of the motion and has to be in the read_groups_id. See https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/motions/access_permissions.py#L75

**Comment by ostcar** [comment]
> The user must be able to see at least one field of the motion

Is there a case where the user can see only some fields? When I understand #80 correctly, then a user can either see all fields or non of the fields.

**Comment by ostcar** [comment]
>  and has to be in the read_groups_id

There is no field `read_groups_id` in the motion_comment.

https://github.com/OpenSlides/OpenSlides/blob/a3dce30e1df12f72316eafa2d42461a5c07487d8/docs/models.yml#L1165

**Comment by ostcar** [comment]
See Motion comment section
