### ISSUE TITLE
Implement read permission: user

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-permission-service#99]

**Comment by normanjaeckel** [comment]
This is hard. Please prepare different levels of read access according to the sets described here: https://github.com/OpenSlides/OpenSlides/blob/master/server/openslides/users/access_permissions.py#L38

Then we look together to all fields and sort them together. Maybe in a phone call.

**Comment by ostcar** [comment]
New fields

Physical person - little
Demo user - little
Role id -little
120 - 134 superuser

**Comment by normanjaeckel** [comment]
See https://github.com/OpenSlides/OpenSlides/pull/5802 Some fields are restricted and only visable inside a meeting.
